#!/usr/bin/env python3
"""Regenerates every page in site_map.PAGES from templates/ + i18n/.

Usage: equipment/build.py
No arguments. Exit 0 on success. Exit 1 with a "page=.. lang=.." message on
the first missing translation key or template error — never writes a
partially-rendered file.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

PLACEHOLDER_RE = re.compile(r"\{\{\s*([a-zA-Z0-9_.]+)\s*\}\}")


def resolve(context, dotted_path):
    value = context
    for part in dotted_path.split("."):
        if not isinstance(value, dict) or part not in value:
            raise KeyError(dotted_path)
        value = value[part]
    if isinstance(value, dict):
        raise KeyError(f"{dotted_path} is a section, not a string")
    return value


def render(template_text, context):
    def _sub(match):
        try:
            return str(resolve(context, match.group(1)))
        except KeyError as e:
            raise KeyError(f"missing translation key: {e.args[0]}") from None
    return PLACEHOLDER_RE.sub(_sub, template_text)


from equipment.site_map import LANGS, PAGES, SITE_URL  # noqa: E402


def nav_href(lang, page_id):
    """Same-language relative link to page_id, as used from a page already
    inside that language's folder (bare filename for fr, prefix-stripped
    filename for en/es)."""
    path = PAGES[page_id][lang]
    if lang == "fr":
        return path
    return path.removeprefix(f"{lang}/")


def asset_prefix(lang):
    """Path prefix to reach repo-root assets (styles.css, script.js, images/)
    from a page written in this language."""
    return "" if lang == "fr" else "../"


def build_nav_context(page_id, lang):
    active_id = PAGES[page_id]["nav_id"]
    ctx = {}
    for nav_id in ("resources", "guidance", "contact", "article"):
        ctx[f"{nav_id}_href"] = nav_href(lang, nav_id)
    for nav_id in ("home", "resources", "guidance", "contact"):
        ctx[f"{nav_id}_active"] = ' class="active"' if active_id == nav_id else ""

    labels = {"fr": "FR", "en": "EN", "es": "ES"}
    other_langs = [l for l in LANGS if l != lang]
    for i, other in enumerate(other_langs, start=1):
        target_path = PAGES[page_id][other]
        href = target_path if lang == "fr" else "../" + target_path
        ctx[f"lang{i}_href"] = href
        ctx[f"lang{i}_label"] = labels[other]
    return ctx


def build_hreflang_context(page_id):
    ctx = {lang: f"{SITE_URL}/{PAGES[page_id][lang]}" for lang in LANGS}
    ctx["x_default"] = f"{SITE_URL}/{PAGES[page_id]['fr']}"
    return ctx


import importlib

TEMPLATES = ROOT / "templates"
GENERATED_HEADER = (
    "<!-- AUTO-GENERATED by equipment/build.py "
    "— edit templates/ and i18n/, not this file. -->\n"
)


class BuildError(Exception):
    pass


def load_strings(lang):
    return importlib.import_module(f"i18n.{lang}").STRINGS


def render_partial(name, context):
    text = (TEMPLATES / "partials" / name).read_text(encoding="utf-8")
    # rstrip: partial files end with a trailing newline like any text file: the
    # page template controls its own blank-line spacing around the {{ }} block,
    # so a newline baked into the partial's own file would double it up.
    return render(text, context).rstrip("\n")


def build_page(page_id, page_info):
    template_text = (TEMPLATES / "pages" / page_info["template"]).read_text(encoding="utf-8")
    for lang in LANGS:
        if lang not in page_info:
            continue
        strings = load_strings(lang)

        base_context = dict(strings)
        base_context["_nav"] = build_nav_context(page_id, lang)
        base_context["_footer"] = {
            "about_href": nav_href(lang, "about"),
            "contact_href": nav_href(lang, "contact"),
        }
        base_context["_hreflang"] = build_hreflang_context(page_id)
        base_context["_asset_prefix"] = asset_prefix(lang)
        base_context["_lang_html"] = lang

        try:
            page_context = dict(base_context)
            page_context["_nav_block"] = render_partial("nav.html", base_context)
            page_context["_footer_block"] = render_partial("footer.html", base_context)
            page_context["_whatsapp_block"] = render_partial("whatsapp-float.html", base_context)

            if page_id in ("home", "guidance"):
                hamann_context = dict(base_context)
                if page_id == "home":
                    hamann_context["_hamann_cta_href"] = nav_href(lang, "guidance")
                    hamann_context["_hamann_cta_label"] = resolve(
                        strings, "pages.home.guidance_teaser.cta"
                    )
                else:
                    hamann_context["_hamann_cta_href"] = nav_href(lang, "contact")
                    hamann_context["_hamann_cta_label"] = resolve(strings, "pages.guidance.cta")
                page_context["_hamann_bio_block"] = render_partial("hamann-bio.html", hamann_context)

            output = render(template_text, page_context)
        except KeyError as e:
            raise BuildError(f"page={page_id} lang={lang}: {e}") from None

        out_path = ROOT / page_info[lang]
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(GENERATED_HEADER + output, encoding="utf-8")


def main():
    try:
        for page_id, page_info in PAGES.items():
            build_page(page_id, page_info)
    except BuildError as e:
        print(f"[FAIL] {e}", file=sys.stderr)
        sys.exit(1)
    print(f"[OK] built {len(PAGES)} pages x up to {len(LANGS)} languages")


if __name__ == "__main__":
    main()
